<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Crypto extends \App\Entity\Crypto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'sigle', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'transactions', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'cotations', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'wallets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'sigle', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'transactions', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'cotations', '' . "\0" . 'App\\Entity\\Crypto' . "\0" . 'wallets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Crypto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getSigle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSigle', []);

        return parent::getSigle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSigle(string $sigle): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSigle', [$sigle]);

        return parent::setSigle($sigle);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactions', []);

        return parent::getTransactions();
    }

    /**
     * {@inheritDoc}
     */
    public function addTransaction(\App\Entity\Transaction $transaction): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTransaction', [$transaction]);

        return parent::addTransaction($transaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTransaction(\App\Entity\Transaction $transaction): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTransaction', [$transaction]);

        return parent::removeTransaction($transaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getCotations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCotations', []);

        return parent::getCotations();
    }

    /**
     * {@inheritDoc}
     */
    public function addCotation(\App\Entity\Cotation $cotation): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCotation', [$cotation]);

        return parent::addCotation($cotation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCotation(\App\Entity\Cotation $cotation): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCotation', [$cotation]);

        return parent::removeCotation($cotation);
    }

    /**
     * {@inheritDoc}
     */
    public function getWallets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWallets', []);

        return parent::getWallets();
    }

    /**
     * {@inheritDoc}
     */
    public function addWallet(\App\Entity\Wallet $wallet): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWallet', [$wallet]);

        return parent::addWallet($wallet);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWallet(\App\Entity\Wallet $wallet): \App\Entity\Crypto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWallet', [$wallet]);

        return parent::removeWallet($wallet);
    }

}
