<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pBtC1xU' shared service.

return $this->privates['.service_locator.pBtC1xU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cRepo' => ['privates', 'App\\Repository\\CryptoRepository', 'getCryptoRepositoryService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'uRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
    'wRepo' => ['privates', 'App\\Repository\\WalletRepository', 'getWalletRepositoryService.php', true],
]);
