<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o3z0mDx' shared service.

return $this->privates['.service_locator.o3z0mDx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
    'user' => ['privates', '.errored..service_locator.o3z0mDx.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.o3z0mDx": it references class "App\\Entity\\User" but no such service exists.'],
]);
