<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yTCe0Hv' shared service.

return $this->privates['.service_locator.yTCe0Hv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'crypto' => ['privates', '.errored..service_locator.yTCe0Hv.App\\Entity\\Crypto', NULL, 'Cannot autowire service ".service_locator.yTCe0Hv": it references class "App\\Entity\\Crypto" but no such service exists.'],
]);
