<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9_yq60R' shared service.

return $this->privates['.service_locator.9_yq60R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cRepo' => ['privates', 'App\\Repository\\CryptoRepository', 'getCryptoRepositoryService.php', true],
    'tRepo' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
    'user' => ['privates', '.errored..service_locator.9_yq60R.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.9_yq60R": it references class "App\\Entity\\User" but no such service exists.'],
    'wRepo' => ['privates', 'App\\Repository\\WalletRepository', 'getWalletRepositoryService.php', true],
]);
