<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::adminRoles' => ['privates', '.service_locator.o3z0mDx', 'get_ServiceLocator_O3z0mDxService.php', true],
    'App\\Controller\\AdminController::adminUsers' => ['privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true],
    'App\\Controller\\CryptoController::index' => ['privates', '.service_locator.DPZbUE8', 'get_ServiceLocator_DPZbUE8Service.php', true],
    'App\\Controller\\CryptoController::showOne' => ['privates', '.service_locator.yTCe0Hv', 'get_ServiceLocator_YTCe0HvService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.sTG20tJ', 'get_ServiceLocator_STG20tJService.php', true],
    'App\\Controller\\TransactionController::adminTransactionsShow' => ['privates', '.service_locator.yKHrXwf', 'get_ServiceLocator_YKHrXwfService.php', true],
    'App\\Controller\\TransactionController::cryptoBuy' => ['privates', '.service_locator.pBtC1xU', 'get_ServiceLocator_PBtC1xUService.php', true],
    'App\\Controller\\TransactionController::cryptoSell' => ['privates', '.service_locator.pBtC1xU', 'get_ServiceLocator_PBtC1xUService.php', true],
    'App\\Controller\\TransactionController::transactionsShow' => ['privates', '.service_locator.9_yq60R', 'get_ServiceLocator_9Yq60RService.php', true],
    'App\\Controller\\UserController::increaseSolde' => ['privates', '.service_locator..NmEFk5', 'get_ServiceLocator__NmEFk5Service.php', true],
    'App\\Controller\\UserController::userCreate' => ['privates', '.service_locator.sTG20tJ', 'get_ServiceLocator_STG20tJService.php', true],
    'App\\Controller\\UserController::userDelete' => ['privates', '.service_locator._T5_KZ6', 'get_ServiceLocator_T5KZ6Service.php', true],
    'App\\Controller\\UserController::userEdit' => ['privates', '.service_locator.Pu8KG5q', 'get_ServiceLocator_Pu8KG5qService.php', true],
    'App\\Controller\\UserController::userShow' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\AdminController:adminRoles' => ['privates', '.service_locator.o3z0mDx', 'get_ServiceLocator_O3z0mDxService.php', true],
    'App\\Controller\\AdminController:adminUsers' => ['privates', '.service_locator.Eh5YPL1', 'get_ServiceLocator_Eh5YPL1Service.php', true],
    'App\\Controller\\CryptoController:index' => ['privates', '.service_locator.DPZbUE8', 'get_ServiceLocator_DPZbUE8Service.php', true],
    'App\\Controller\\CryptoController:showOne' => ['privates', '.service_locator.yTCe0Hv', 'get_ServiceLocator_YTCe0HvService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.sTG20tJ', 'get_ServiceLocator_STG20tJService.php', true],
    'App\\Controller\\TransactionController:adminTransactionsShow' => ['privates', '.service_locator.yKHrXwf', 'get_ServiceLocator_YKHrXwfService.php', true],
    'App\\Controller\\TransactionController:cryptoBuy' => ['privates', '.service_locator.pBtC1xU', 'get_ServiceLocator_PBtC1xUService.php', true],
    'App\\Controller\\TransactionController:cryptoSell' => ['privates', '.service_locator.pBtC1xU', 'get_ServiceLocator_PBtC1xUService.php', true],
    'App\\Controller\\TransactionController:transactionsShow' => ['privates', '.service_locator.9_yq60R', 'get_ServiceLocator_9Yq60RService.php', true],
    'App\\Controller\\UserController:increaseSolde' => ['privates', '.service_locator..NmEFk5', 'get_ServiceLocator__NmEFk5Service.php', true],
    'App\\Controller\\UserController:userCreate' => ['privates', '.service_locator.sTG20tJ', 'get_ServiceLocator_STG20tJService.php', true],
    'App\\Controller\\UserController:userDelete' => ['privates', '.service_locator._T5_KZ6', 'get_ServiceLocator_T5KZ6Service.php', true],
    'App\\Controller\\UserController:userEdit' => ['privates', '.service_locator.Pu8KG5q', 'get_ServiceLocator_Pu8KG5qService.php', true],
    'App\\Controller\\UserController:userShow' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
