<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJVRDbie\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJVRDbie/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJVRDbie.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJVRDbie\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJVRDbie\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JVRDbie',
    'container.build_id' => 'fc8b106a',
    'container.build_time' => 1552305905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJVRDbie');
